version: "3.9"
services:
    runproj_database:
        image: postgres
        environment:
            POSTGRES_USER: runproj
            POSTGRES_PASSWORD: mysecretpassword
            POSTGRES_DB: runproj
        ports:
            - "5432:5432"

    runproj_api:
        build: .
        ports:
            - "3000:3000"
        environment:
            DB_HOST: runproj_database
            DB_USER: runproj
            DB_PASSWORD: mysecretpassword
            DB_DATABASE: runproj
            DB_PORT: 5432
            DB_CONNECT_MAX_TRIES: 3
        depends_on:
            - runproj_database
        links:
            - runproj_database
